### ISSUE TITLE
Initial Setup

### ISSUE THREAD

**Issue by macdoos** [macdoos/matrix#1]
Initialize the Git repository for the project and set up the development environment. This includes:
- [x] Creating a virtual environment
- [x] Installing necessary dependencies
- [x] Setting up configuration files
- [x] Basic directory structure and a README file

**Comment by macdoos** [comment]
@ahmeddelattarr Nice work overall. The basic functionality is working fine.

**TODO:**
1. Don't use names like 'second_task' for directories. Use a conventional file structure, such as `src`, `build`, etc.
2. Don't use punctuation (;) in branch names. Use either kebab case or camel case for naming without punctuation.
3. Remove comments. If something really needs to be explained, mention it in the README. Otherwise, the code should be simple and readable.
4. Create a new branch and open a pull request for all of the above changes. [Here's](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request) how to do it.
